#!/bin/bash

sourceFile=$1

destination=$2

if [ $1 == "-h" ]; then
	echo "Usage: multi_cp source_file destination_directories"
	exit 0
fi

mkdir -p $destination


for dir in ~/bin/*/ ; do
	echo $dir
done


